---
title: "ggplot2"
author: "Katherine"
date: "8/5/2019"
output: html_document
---

# Learning ggplot1

We are learning ggplot2 and it's going to be amazing 

```{r, include=FALSE}
library (tidyverse)
ohi_data <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/OHI_global_data.csv")
head (ohi_data)
summary (ohi_data)
table (ohi_data$georegion_one)
table (ohi_data$georegion_two)
```

```{r}
ggplot(data=ohi_data, aes(x=OHI_score, y=HDI)) +
  geom_point()

ggplot(data=ohi_data, aes (x=georegion_one, y=OHI_score)) +
  geom_jitter(width=0.2)

ggplot(data = ohi_data, aes(x = georegion_one)) + 
  geom_bar() 


```

```{r}
ohi_summary <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/OHI_scores_georegion_summary.csv")

ohi_summary
ggplot(data = ohi_summary, aes(x = georegions, y = OHI_score_average)) + 
  geom_bar(stat="identity") +
  geom_jitter(data=ohi_data, aes(x=georegion_one, y=OHI_score))

ggplot(data = ohi_data, aes(y=OHI_score, x = HDI, color=georegion_one)) +
  geom_point()

ggplot(data = ohi_data, aes(x = OHI_score, y = HDI, size = coastal_pop)) + 
  geom_point()

ggplot(data = ohi_data, aes(x = OHI_score, y = HDI, color = coastal_pop)) + 
  geom_point()
ggplot(data = ohi_data, aes(x = OHI_score, y = HDI, label=country)) + 
  geom_point(aes(x = OHI_score, y = HDI)) 
ggplot(data = ohi_data, aes(x = OHI_score, y = HDI, label=country)) + 
  geom_point(aes(x = OHI_score, y = HDI)) +
  geom_text()
```
## cleaning things up 

Use theme_

```{r}
ggplot(data=ohi_data, aes(x=OHI_score, y=HDI)) +
  geom_point() +
  theme_bw()
```

### Scatter themed

```{r}
source('https://raw.githubusercontent.com/OHI-Science/ohiprep/master/src/R/scatterTheme.txt')       

ggplot(data = ohi_data, aes(x = OHI_score, y = HDI)) + 
  geom_point() + 
  scatterTheme
```
### labels 

```{r}
ggplot(data = ohi_data, aes(y = OHI_score, x = HDI, color=georegion_one)) + 
  geom_point() + 
    labs(y = "OHI score, 2017",
       x = "Human Development Index",
       title = "Countries with high human development have more sustainable oceans",
      color = "Georegion") +  
     theme_bw()
```

### making a histogram 

```{r}
histogram_plot <- ggplot(data = ohi_data, aes(x = HDI)) + 
  geom_histogram() 

histogram_plot +
  geom_histogram(fill="lightgrey")

histogram_plot +
  labs (x= "OHI Score in 2017",
        y="Number of countries", title= "OHI of countries")

```

```{r}


```
 ### AES functions 
 
```{r}
ggplot(data=ohi_summary, aes (x=georegions, y=OHI_score_average)) +
  geom_bar(stat="identity", fill="lightgrey") +
  geom_jitter (data=ohi_data, aes (x=georegion_one, y=OHI_score), color="red", size=3, alpha=0.3) +
  theme_bw ()



```
```{r}
my_palate <- brewer.pal (n=9, "YlOrRd")
my_palate
ggplot(data = ohi_data, aes(x = OHI_score, y = OHI_trend, color = HDI)) + 
  geom_point(size =3) +
  scale_colour_gradientn(colors = my_palate)
```
```{r}
display.brewer.all()
```
 
